apiVersion: v1
kind: Namespace
metadata:
  name: ibm-sls
  annotations:
    argocd.argoproj.io/sync-wave: "-30"
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: ibm-sls-operator-group
  namespace: ibm-sls
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  targetNamespaces:
    - ibm-sls
---
