apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ibm-entitlement-key
  namespace: openshift-marketplace
spec:
  encryptedData:
    .dockerconfigjson: AgAugS5zYIlc98u3PRY1Dhfr4SX9keQzsTwdWbbcgUp8csgL4IKbAKyiIKgka5pKA5kU6egLycQYktwDGVGxHb3LNw3nCFkX6nPva1QVNdH8aJZGYn4Xuo4LxL86EI0v10gJG8vdWuwHoBMM4ZrWAnptwPCfvlnUVmzjKmRA/EbQCEBvR4YxNdmkcJ3di+SwupODFDhQsbGddLm78A4NF3yIlPIc8F9wmcw2aYZG2xpYLRN7Qvq/n1kbuGTKBzTJHBZDRJSs2ajuwAtny3OJZTdryZPDxkEKeHFumX51rVjNmDAhov3Mo5iBfdRdY1A4lJre7svZP2IuEYQvylQlmNhtQd0HGa4rphZqJT2q2ZDN6UQQomGdfZw5ODvyyzoX+K22XTEoyGU3WSC4RfWlUJKg/HaSEe9zU302RqhQP9t/ouTPv69ROvOhN2dbGZAHtf77YYSsqIOAjXidRUEWhqDr7PTfNzk8xia3awAXfWLa+wzr415NBV3K5m0M8SPPX7PXG4L2NJsw0604Nv7RBN6ZcvWK17zSZY33pckPvV7p/B70ObsHcXp4UnzHlO5PRHaexWb7CsfvXvFKOVIikj8UYZxQb5WcDIMNIU1KRLTMbBIw4shA+uVJXThQhg+/UcMMbW1l/4J9Z5ai77q5u25JucOjEXjy7yw6n79QuE5ok3BNMdxlXMlPr4TkOkC+RsyAn37mtTJsOV1+EOGfHO35OP7gs7OHG85mtGFFB/ebLV6qFlTg+oWyyRfdNLSCNy+m2Ul9r3EoBQTKAO1kRLymTmZKTyrOWrE+O4QireDAlkC3mGLjMjndGhCjXD7UyZHtUKW7VwYO+BZSqcV0kCux4E+WqPA+BK30+FjL+ngkrFrJ29i43Uwgs6BEXXhV9ExHhudM4TsAxFQVxS+G9PZ8WBnB5moMkAuj2wOJoD/iK64wt6I52vcSh6+EQEIzSr5//RC6gSMmHPntpjWbC0GWpmcpEu/pzDCbBATa/or1XQhmtp0ty0BG9kZSaq0rjvwPSAr55rMVwtQSTPotTwtrjpCt0KLrVgBpANH/CjmeIGVunm2hyP25mW4/47aNe/4DvjAlScrCLkR6NQ11qmOuymteIdvmABRvp9FVMXiifbHwIChO4KpsnDwFFS7OPnDMDfUIerXBrH+rtaezHPp6mUzOS8dMnWOdT2/gS3tO7hX5chwhb2XP2zTvcA6Nhg3kb/tCDAU9rg6Wrrae+VO+uMvlG3JPEauEnq+Hb7Djytr+A6zIrbUby1LUVhmkYLQxJiuIuvXr3awxLYkukJTLtjYYjY9JownhQZ79ZpPqa6Svx8D2INRQ5X4pG7RIYt3U
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: ibm-entitlement-key
      namespace: openshift-marketplace
    type: kubernetes.io/dockerconfigjson

