apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongo-ce-password
  namespace: mongo
spec:
  encryptedData:
    password: AgBYx8ixoB/OU7rYMCtDDYkXQ5sjorDDF57ZXOWmTcC2r2zk4h48RfkqLLOuHKKXXpK1o1YmWMQrtTfM6+4ClbHKiZFQdoEdthjGHtpkOOte43TvwZBuzzVmyBX3Lq4FWwNdZ9DvIP96WeONifGEFGbcAGyItWR2mjlzVgO5FBOOk84HyEP+fqSawoZ7mwc81xfbzW7l/lAnlVKVro+Gv+uJpcBTWLfej9wjMmHQLOwH1ZQfuemqsTwmvdzvyDg8Woc41wpeSqIieDOGqxnu/TpZW64a8MVys/3ySWvX7K6ABoXYyjh+4wbdkm8KONGcxe1lyiPV0EERrpcxF+wWpjdBRJXtzo9imzP+r+rDKANWZ49gKQA2aeY7roK4ccE+XqbalMz4G+DYCIPXMhOyxIwMZprwRce2c6V7KVzry+KnXbks8MiRul0sohx1girZDMEnTf7yGZeidslA3nIxsJVnfCuaZ7ThsqY8HSPSSjC+tZ8x3/kawi+btRLK0tdfbgGvMNIejto3DDa+ftiyZIBbElNoUEs0qHaQdtME+VpAEDxlQEnGrvOwyCXTnsU++LaeTgNEFOk3A9AjNQNZRCigl0HrY54s/A26SVG52NiyNwzojhvafaonUFEyGGkgmnZLk5uqgb6qv9Bm3SRQYQUZ2buPBY6WCK3zsfYhHbB83vTFMi6TJM103LcdOmSDckGUeP4dg5pSuw==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: mongo-ce-password
      namespace: mongo

