apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - base/cert-manager-certmgr.yaml
  - base/mongo-mongodb-kubernetes-operator-rbac.yaml
  - base/mongo-mongodb-kubernetes-operator-sa.yaml
  - base/namespace-mongo.yaml
  - base/openshift-marketplace-ibm-catalogs.yaml
