apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-certmgr
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: 1-infrastructure
  source:
    path: payload/1-infrastructure/namespace/cert-manager/certmgr
    repoURL: https://github.com/cloud-native-toolkit-test/gitops-cp-sls-ocp4
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences: []
