apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongo-mongodb-kubernetes-operator-sa
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: mongo
    server: https://kubernetes.default.svc
  project: 1-infrastructure
  source:
    path: payload/1-infrastructure/namespace/mongo/mongodb-kubernetes-operator-sa
    repoURL: https://github.com/cloud-native-toolkit-test/gitops-cp-sls-ocp4
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
    - jsonPointers:
        - /imagePullSecrets
        - /secrets
      kind: ServiceAccount
