apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongo-mongo-ce-sa-rbac
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: mongo
    server: https://kubernetes.default.svc
  project: 1-infrastructure
  source:
    path: payload/1-infrastructure/namespace/mongo/mongo-ce-sa-rbac
    repoURL: https://github.com/cloud-native-toolkit-test/gitops-cp-sls-ocp4
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences: []
